Shift click to select multiple projects to compare
green-coding-berlin/green-metrics-tool pull request #293
Opened 2023-05-11 14:13 UTC by djesic

2023-05-12 09:05 UTC, ribalba requested changes

2023-05-12 09:05 UTC, ribalba commented on frontend/js/index.js
> +                let low = i; let high=j;
Why are you introducing `low` and `high` here? Couldn't you continue using `i` or `j` ? Or rename them?

2023-05-12 09:10 UTC, djesic commented on frontend/js/index.js
> +
Full disclosure, I copied the function over from stack overflow 😅 
I'll review it and make the changes

2023-05-15 07:57 UTC, ribalba commented on frontend/js/index.js
> +                let check_or_uncheck = this.checked;
This variable is probably not needed anymore. Did a quick fix

2023-05-15 08:01 UTC, merged