MCP39F511N metrics provider
green-coding-berlin/green-metrics-tool pull request #429
Opened 2023-08-16 08:37 UTC by ArneTR

@ribalba Can you give the C code a quick read.

As said in the file: I am including a library of unknown original origin.

    This file is mostly copied from https://github.com/osmhpi/pinpoint/blob/master/src/data_sources/mcp_com.c
    Credits to Sven Köhler and the OSM group from the HPI

    In case the file is not original work: Possible prior origins of the file are unknown. However it is an implementation
    of the protocol defined here:
    - https://www.microchip.com/en-us/development-tool/ADM00706
    - https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/DataSheets/20005473B.pdf

2023-08-31 08:40 UTC, ribalba requested changes
Just an initial quick read. Is this something we want to maintain for the future? The I would probably refactor it. I can do this :)

2023-08-31 08:40 UTC, ribalba commented on metric_providers/psu/energy/ac/mcp/machine/source.c
> +    memcpy(command_packet + 2, cmd, cmd_length);
`cmd` and `cmd_length` are not checked if they fit into cmd

2023-08-31 08:40 UTC, ribalba commented on metric_providers/psu/energy/ac/mcp/machine/source.c
> +    command_packet[i] = checksum;
why if `cmd_length` is > 80

2023-08-31 08:40 UTC, ribalba commented on metric_providers/psu/energy/ac/mcp/machine/source.c
> +    len = write(fd, command_packet, cmd_length + 3);
Why is fd passed as a parameter if it is defined globally?

2023-08-31 08:40 UTC, ribalba commented on metric_providers/psu/energy/ac/mcp/machine/source.c
> +const unsigned char f511_read_active_power2[] = { 0x41, 0x0, 0x1a, 0x4E, 4 };
What is the difference between these read power chars?

2023-10-20 13:31 UTC, ArneTR commented
Updated. @ribalba Can you give it another look?

I clarified in the code what the original author is doing, although some implementations are not documented and cannot be checked completely

2023-10-20 13:44 UTC, ArneTR commented
I will merge it in for now, please put your comments in here if you have any

2023-10-20 13:44 UTC, merged