initial hog database backend
green-coding-berlin/green-metrics-tool pull request #470
Opened 2023-09-20 11:57 UTC by ribalba

This is the first version of the hog backend. 

I still haven't written the migration script for the DB as the schema might change so you will need to create a new DB.

2023-09-22 08:00 UTC, ArneTR requested changes

2023-09-22 08:00 UTC, ArneTR commented on frontend/js/hog-details.js
> +            let zoomFactor = 4;
all const?

2023-09-22 08:00 UTC, ArneTR commented on frontend/js/hog-details.js
> +                let dataZoomOption = myChart.getOption().dataZoom[0];
can apart from firstvalue and lastvalue not all be const?

2023-09-22 08:02 UTC, ArneTR commented
Very nice and clean code. I found only some remarks of which many are open to discuss.

The main discussion point I put separately: Shall we call the endpoints and internal namings still hog, or shall we here also move to power-hog?

An argument can be made that in the future there can be other hogs, so keeping the endpoint generic might not be the worst idea ...?

2023-09-25 14:34 UTC, ribalba commented on api/api.py
> +            _ = Measurement(**measurement_data)
I couldn't find a way to decompress the data string for FastAPI error handling to work. Or what do you mean with the 422 validation?

Good point now also returns the exception.

2023-09-25 14:38 UTC, ribalba commented on api/api.py
> +                'combined_power': int(measurement_data['processor'].get('combined_power', 0) * measurement_data['elapsed_ns'] / 1_000_000_000.0),
to get mJ from mW

totally right. Should be combined_energy as the DB field is.

2023-09-25 14:41 UTC, ribalba commented on api/api.py
> +                'combined_power': int(measurement_data['processor'].get('package_joules', 0) * 1_000),
we save everything in mJ (millijoule) but intel processors give us joules. I made the comment more explicit

2023-09-25 14:42 UTC, ribalba commented on api/api.py
> +                'gpu_energy': int(measurement_data['processor'].get('igpu_watts', 0) * measurement_data['elapsed_ns'] / 1_000_000_000.0 * 1_000),
to get from watts to millijoule.

2023-09-25 14:54 UTC, ribalba commented on api/api.py
> +    if data is None:
- I refactored the code to make it clearer what it does. 
- I also didn't know that fetch_all always returns a list. We have that check quite a few times:
```
    data = DB().fetch_all(query, (run_id,))
    if data is None or data == []:
        return Response(status_code=204) # No-Content
```
shall I refactor this everywhere?

- I like `if x is None:` more than `if not x:`. Maybe we should define a std for our code base?

2023-09-25 14:56 UTC, ribalba commented on api/api.py
> +    if tasks_data is None:
What do you mean with `==`?

2023-09-25 14:57 UTC, ribalba commented on api/api.py
> +        coalitions_data = []
If it is empty it is ok? I want the list to be empty if there is no data

2023-09-25 15:01 UTC, ribalba commented on api/object_specifications.py
> +    diskio_bytesread: int = 0
See comment below: https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields

If you have 
```
diskio_bytesread: Optional[int]
```
the key is still required. 

In this case I wanted to also have the `diskio_bytesread` set to 0 as I was planing on using the validated object at some stage. Added the optional keyword to make it clearer.

2023-09-25 15:22 UTC, ribalba commented on docker/structure.sql
> +CREATE INDEX idx_coalition_name ON hog_coalitions(name);
I think this is a difficult one to spot. I know that sometimes a `group by` is done by sorting. I set an index here to speed up the `group by name`. I don't know if the DB is smart enough to switch to a filter if we set a hash index here. Good little test to set up :)

2023-09-25 15:25 UTC, ribalba commented on frontend/js/hog-details.js
> +    var mData
totally

2023-09-26 13:29 UTC, ArneTR requested changes

2023-09-26 13:29 UTC, ArneTR commented on api/api.py
> +    if data is None:
@ribalba Remeber that data can be None in case where the DB is not available or the Select query is broken

2023-09-29 11:01 UTC, merged