Import refactoring
green-coding-berlin/green-metrics-tool pull request #476
Opened 2023-09-22 16:19 UTC by ArneTR

First version that uses `.pth` files in the `venv` to set a default include path

Downside: Now venvs are mandatory and must be activated for the GMT to work

2023-09-22 22:34 UTC, ArneTR commented
The tests are failing, but the code itself should work.

@ribalba Can you test if the new install script works in Fedora?

@dan-mm Can you look at the tests please. Major change here is that the tests folder has been renamed from "test" to "tests", because now loading by folder Python can get confused with modules and apparently there is a "test" module, but no "tests" module in the standard-lib

I am unsure if that is due to the tests itself or with the instrumentation on Github that the renaming leads to errors

2023-09-25 07:15 UTC, ribalba commented
What a refactor. Works on Fedora and giving the commit a quick read it all looks A OK.

2023-09-25 07:15 UTC, ribalba approved these changes

2023-09-25 08:22 UTC, ribalba commented
@ArneTR I did a tiny refactor the the pylint checks and pushed it to this branch.

2023-09-25 11:35 UTC, dan-mm commented
Updated everything test related to reflect the new path. Just a few small changes here and there.

If I turn off the xgboost model in my test-config, everything else passes locally. The workflow should also be good too, though its currently also failing because of the xgboost model (and there's always a chance this hides a failure further down the pipeline.... but I don't expect that to be the case here)

2023-09-25 11:41 UTC, ArneTR commented
so what is the plan? I do not want to merge it if it fails with the XGBoost. That model should work.

Can you post the error here?

2023-09-25 11:56 UTC, dan-mm requested changes

2023-09-25 11:56 UTC, dan-mm commented on metric_providers/psu/energy/ac/xgboost/machine/provider.py
>  import model.xgb as mlmodel
I get an error here when I try to run the runner with the XGBoost model enabled:

```
>   import model.xgb as mlmodel
E   ModuleNotFoundError: No module named 'model'

../metric_providers/psu/energy/ac/xgboost/machine/provider.py:5: ModuleNotFoundError
```
The model referenced in this branch is on the same commit as the one in main: https://github.com/green-coding-berlin/spec-power-model/tree/95f13ad95ced02350c75841616306115a1402e93

Does the spec-power-model need an update for this too? I see this error both in tests, and using the runner.py manually.

2023-09-25 12:34 UTC, dan-mm approved these changes

2023-09-28 16:00 UTC, ArneTR commented
Status from today: It is unclear why the `lib.db` import is not working. This will be fixed tomorrow morning by Dan

2023-09-30 09:30 UTC, merged